# Generated by Django 6.0 on 2025-12-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('working_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('early_departure_days', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'verbose_name_plural': 'Monthly Summaries',
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
