# Generated by Django 6.0 on 2025-12-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_employee_department_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift_end',
            field=models.TimeField(blank=True, help_text='Expected departure time (e.g., 18:30)', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start',
            field=models.TimeField(blank=True, help_text='Expected arrival time (e.g., 09:30)', null=True),
        ),
    ]
