# Generated by Django 6.0 on 2025-12-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employee_shift_end_employee_shift_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(help_text='Expected arrival time (e.g., 09:30)')),
                ('shift_end', models.TimeField(help_text='Expected departure time (e.g., 18:30)')),
                ('effective_from', models.DateField(help_text='Date from which this shift timing applies')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_history', to='attendance.employee')),
            ],
            options={
                'verbose_name_plural': 'Shift Histories',
                'ordering': ['-effective_from'],
            },
        ),
    ]
