# Generated by Django 6.0 on 2025-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_employee_is_active_employee_leaving_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='person_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('person_id', 'name')},
        ),
    ]
