# Generated by Django 6.0 on 2025-12-20 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_employee_person_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck when employee leaves the company')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, help_text='Date when employee left the company', null=True)),
            ],
            options={
                'verbose_name': 'Remote Employee',
                'verbose_name_plural': 'Remote Employees',
                'unique_together': {('extension_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RemoteCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('answered_calls', models.IntegerField(default=0)),
                ('no_answered', models.IntegerField(default=0)),
                ('busy', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('voicemail', models.IntegerField(default=0)),
                ('total_ring_duration', models.DurationField(blank=True, null=True)),
                ('total_talk_duration', models.DurationField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent')], default='absent', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.remoteemployee')),
            ],
            options={
                'verbose_name': 'Remote Call Record',
                'verbose_name_plural': 'Remote Call Records',
                'ordering': ['-date', 'employee__name'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RemoteMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('present_days', models.IntegerField(default=0)),
                ('half_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('total_calls', models.IntegerField(default=0)),
                ('total_talk_time', models.DurationField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.remoteemployee')),
            ],
            options={
                'verbose_name': 'Remote Monthly Summary',
                'verbose_name_plural': 'Remote Monthly Summaries',
                'ordering': ['-year', '-month', 'employee__name'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
