# Generated by Django 6.0 on 2025-12-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remoteemployee_remotecallrecord_remotemonthlysummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysummary',
            old_name='early_departure_days',
            new_name='half_days',
        ),
    ]
