# Generated by Django 6.0 on 2025-12-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_add_holiday_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='portal_password',
            field=models.CharField(blank=True, help_text='Hashed password for employee portal login', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='remoteemployee',
            name='portal_password',
            field=models.CharField(blank=True, help_text='Hashed password for employee portal login', max_length=128, null=True),
        ),
    ]
