# Generated by Django 6.0 on 2025-12-25 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_employee_portal_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(help_text='Date of early leave')),
                ('leaving_time', models.TimeField(help_text='Time when leaving the office')),
                ('destination', models.CharField(help_text='Where they are going', max_length=255)),
                ('customer_name', models.CharField(help_text='Customer/Client they are meeting', max_length=255)),
                ('reason', models.TextField(blank=True, help_text='Additional details or reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin comments on the request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
                ('remote_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.remoteemployee')),
            ],
            options={
                'verbose_name': 'Early Leave Request',
                'verbose_name_plural': 'Early Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
