# Generated by Django 6.0 on 2025-12-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_earlyleaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlyleaverequest',
            name='return_time',
            field=models.TimeField(blank=True, help_text='Estimated time of return', null=True),
        ),
    ]
