# Generated by Django 6.0 on 2025-12-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_attendancerecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, help_text="Office location (e.g., 'Dubai HQ', 'Abu Dhabi Branch')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.CharField(blank=True, help_text="Team name (e.g., 'Sales', 'Engineering', 'Support')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='remoteemployee',
            name='location',
            field=models.CharField(blank=True, help_text="Office location (e.g., 'Dubai HQ', 'Abu Dhabi Branch')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='remoteemployee',
            name='team',
            field=models.CharField(blank=True, help_text="Team name (e.g., 'Sales', 'Engineering', 'Support')", max_length=100, null=True),
        ),
    ]
