# Generated by Django 6.0 on 2025-12-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_employee_location_employee_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Coordinator', 'Coordinator'), ('Admin', 'Admin')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='remoteemployee',
            name='department',
            field=models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Coordinator', 'Coordinator'), ('Admin', 'Admin')], max_length=100, null=True),
        ),
    ]
