# Generated by Django 6.0 on 2025-12-30 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('medical', 'Medical Leave'), ('annual', 'Annual Leave'), ('casual', 'Casual Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(help_text='Reason for leave request')),
                ('document', models.FileField(blank=True, help_text='Required for Sick and Medical leave', null=True, upload_to='leave_documents/%Y/%m/')),
                ('requested_days', models.PositiveIntegerField(help_text='Number of days requested')),
                ('approved_days', models.PositiveIntegerField(blank=True, help_text='Number of days approved (can be less than requested)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin comments or rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'start_date'], name='attendance__employe_cd936f_idx'), models.Index(fields=['status'], name='attendance__status_6e3dfd_idx')],
            },
        ),
    ]
